export const fonts = {
  'Prompt-Black': require('./src/assets/fonts/Prompt-Black.ttf'),
  'Prompt-BlackItalic': require('./src/assets/fonts/Prompt-BlackItalic.ttf'),
  'Prompt-Bold': require('./src/assets/fonts/Prompt-Bold.ttf'),
  'Prompt-BoldItalic': require('./src/assets/fonts/Prompt-BoldItalic.ttf'),
  'Prompt-ExtraBold': require('./src/assets/fonts/Prompt-ExtraBold.ttf'),
  'Prompt-ExtraBoldItalic': require('./src/assets/fonts/Prompt-ExtraBoldItalic.ttf'),
  'Prompt-ExtraLight': require('./src/assets/fonts/Prompt-ExtraLight.ttf'),
  'Prompt-ExtraLightItalic': require('./src/assets/fonts/Prompt-ExtraLightItalic.ttf'),
  'Prompt-Italic': require('./src/assets/fonts/Prompt-Italic.ttf'),
  'Prompt-Light': require('./src/assets/fonts/Prompt-Light.ttf'),
  'Prompt-LightItalic': require('./src/assets/fonts/Prompt-LightItalic.ttf'),
  'Prompt-Medium': require('./src/assets/fonts/Prompt-Medium.ttf'),
  'Prompt-MediumItalic': require('./src/assets/fonts/Prompt-MediumItalic.ttf'),
  'Prompt-Regular': require('./src/assets/fonts/Prompt-Regular.ttf'),
  'Prompt-SemiBold': require('./src/assets/fonts/Prompt-SemiBold.ttf'),
  'Prompt-SemiBoldItalic': require('./src/assets/fonts/Prompt-SemiBoldItalic.ttf'),
  'Prompt-Thin': require('./src/assets/fonts/Prompt-Thin.ttf'),
  'Prompt-ThinItalic': require('./src/assets/fonts/Prompt-ThinItalic.ttf'),
};
